
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Mini_Pjt_Shopping.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Compare
{

    public int Compare_Id { get; set; }

    public Nullable<int> User_Id { get; set; }

    public Nullable<int> Prod_Id { get; set; }

    public Nullable<int> Category_Id { get; set; }



    public virtual Product Product { get; set; }

    public virtual User User { get; set; }

    public virtual Category Category { get; set; }

}

}
