

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Mini_Pjt_Shopping.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class MiniProject_ShopEntities : DbContext
{
    public MiniProject_ShopEntities()
        : base("name=MiniProject_ShopEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Retailer> Retailers { get; set; }

    public virtual DbSet<Update_Products> Update_Products { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    public virtual DbSet<Compare> Compares { get; set; }


    public virtual ObjectResult<GetAllPdts_Result> GetAllPdts()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPdts_Result>("GetAllPdts");
    }


    public virtual ObjectResult<GetCategory_Result> GetCategory(string catname)
    {

        var catnameParameter = catname != null ?
            new ObjectParameter("catname", catname) :
            new ObjectParameter("catname", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategory_Result>("GetCategory", catnameParameter);
    }


    public virtual ObjectResult<GetAllCategory_Result> GetAllCategory()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCategory_Result>("GetAllCategory");
    }


    public virtual ObjectResult<GetOneCategory_Result> GetOneCategory(Nullable<int> catid)
    {

        var catidParameter = catid.HasValue ?
            new ObjectParameter("catid", catid) :
            new ObjectParameter("catid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneCategory_Result>("GetOneCategory", catidParameter);
    }


    public virtual ObjectResult<GetWishlist_Result> GetWishlist(Nullable<int> userid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWishlist_Result>("GetWishlist", useridParameter);
    }


    public virtual int AddToWishlist(Nullable<int> userid, Nullable<int> prodid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        var prodidParameter = prodid.HasValue ?
            new ObjectParameter("prodid", prodid) :
            new ObjectParameter("prodid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddToWishlist", useridParameter, prodidParameter);
    }


    public virtual ObjectResult<GetWishItem_Result> GetWishItem(Nullable<int> prodid)
    {

        var prodidParameter = prodid.HasValue ?
            new ObjectParameter("prodid", prodid) :
            new ObjectParameter("prodid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWishItem_Result>("GetWishItem", prodidParameter);
    }


    public virtual int AddTOCart(Nullable<int> userid, Nullable<int> prodid, Nullable<int> prod_qty, Nullable<decimal> prod_price)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        var prodidParameter = prodid.HasValue ?
            new ObjectParameter("prodid", prodid) :
            new ObjectParameter("prodid", typeof(int));


        var prod_qtyParameter = prod_qty.HasValue ?
            new ObjectParameter("prod_qty", prod_qty) :
            new ObjectParameter("prod_qty", typeof(int));


        var prod_priceParameter = prod_price.HasValue ?
            new ObjectParameter("prod_price", prod_price) :
            new ObjectParameter("prod_price", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTOCart", useridParameter, prodidParameter, prod_qtyParameter, prod_priceParameter);
    }


    public virtual ObjectResult<GetCart_Result> GetCart(Nullable<int> userid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCart_Result>("GetCart", useridParameter);
    }


    public virtual ObjectResult<sp_GetAllPdt_Result> sp_GetAllPdt()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllPdt_Result>("sp_GetAllPdt");
    }


    public virtual ObjectResult<sp_GetOnePdt_Result> sp_GetOnePdt(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetOnePdt_Result>("sp_GetOnePdt", idParameter);
    }


    public virtual ObjectResult<sp_Pdts_Of_One_Category_Result> sp_Pdts_Of_One_Category(Nullable<int> cat_id)
    {

        var cat_idParameter = cat_id.HasValue ?
            new ObjectParameter("cat_id", cat_id) :
            new ObjectParameter("cat_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Pdts_Of_One_Category_Result>("sp_Pdts_Of_One_Category", cat_idParameter);
    }


    public virtual ObjectResult<GetCartItem_Result> GetCartItem(Nullable<int> userid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItem_Result>("GetCartItem", useridParameter);
    }


    public virtual ObjectResult<GetCartItems_Result> GetCartItems(Nullable<int> userid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItems_Result>("GetCartItems", useridParameter);
    }


    public virtual int decQty(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("decQty", idParameter);
    }


    public virtual int incQty(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("incQty", idParameter);
    }


    public virtual ObjectResult<Nullable<decimal>> CalTotal(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CalTotal", idParameter);
    }


    public virtual int AddToCompare(Nullable<int> userid, Nullable<int> prodid, Nullable<int> catid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        var prodidParameter = prodid.HasValue ?
            new ObjectParameter("prodid", prodid) :
            new ObjectParameter("prodid", typeof(int));


        var catidParameter = catid.HasValue ?
            new ObjectParameter("catid", catid) :
            new ObjectParameter("catid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddToCompare", useridParameter, prodidParameter, catidParameter);
    }


    public virtual ObjectResult<GetComparelist_Result> GetComparelist(Nullable<int> userid)
    {

        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetComparelist_Result>("GetComparelist", useridParameter);
    }


    public virtual int reduceQty(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("reduceQty", idParameter);
    }


    public virtual int reduceQty1(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("reduceQty1", idParameter);
    }

}

}

