
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Mini_Pjt_Shopping.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int Order_Id { get; set; }

    public Nullable<int> User_id { get; set; }

    public Nullable<int> Prod_id { get; set; }

    public Nullable<decimal> Prod_Price { get; set; }

    public Nullable<int> Prod_Quantity { get; set; }

    public Nullable<int> Retail_id { get; set; }



    public virtual Product Product { get; set; }

    public virtual Retailer Retailer { get; set; }

    public virtual User User { get; set; }

}

}
